---
title: "Literature Review"
author: "Vik Sharma"
date: "3/30/2022"
output: pdf_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Papers on Trend Following 

##**[@ClareSeatonThomas2012] - Breaking into the blackbox**

The authors test whether a simple trend following strategy can outperform a buy 
and hold strategy on the S&P500. They alter the complexity of rules, trading
frequency, and risk management rules, of the underlying strategy and analyze
whether the modifications can improve returns. Finally, the technical strategy 
is compared with strategies that use fundamental metrics. 

The authors analyze the following types of indicators:

1) Simple movig averages (10 to 450 day SMA analyzed)

2) Moving average crossover (25/50 to 150/350 day crossovers analyzed)

3) Breakout signals - index value at a 'x' day high (x ranges from 10 to 450)

The authors find that:

i) simple indicators and signals such as the 200 day SMA dominate the long only
investment strategy, 

ii) monthly trading frequency is superior to any higher trading frequencies, 

iii) there is no benefit to using stop-loss rules, 

iv) there is no evidence suggesting that fundamental metrics provide superior
trading signals than technical indicators. 


##**[@lo2000foundations] - Foundations of Technical Analysis** 

The authors analyze a systematic and automatic approach to technical analysis 
using nonparametric kernel regression. They apply this method to a large number 
of US stocks from 1962 to 1996. They compare the unconditional empirical 
distribution of stock returns to the conditional distribution, conditional to 
specific technical 'patterns' such as 'head and shoulders' and 'double bottom'. 
They find that several technical indicators provide incremental information and 
may have practical value. 

1) The authors estimate the nonlinear relationship between time and prices using 
the following equation: 

$$ P_{t} = m(X_{t}) + \epsilon_t $$
*$X_{t}$ is a state variable, which, in this case, is set equal to time* 

2) Smoothing Estimators try to smooth the noise out to identify historical 
patterns. Nadaraya-Watson kernel estimator is used to generate an estimate 
($\hat{m}(.)$) of true underlying price history (${P_{t}}$)

3) Automated technical algorithm 
a) Define technical patterns in terms of geometric properties 
b) Construct kernel estimator ($\hat{m}(.)$) to numerically identify geometric 
properties 
c) Analyze ($\hat{m}(.)$) for occurences of each technical indicator 

The authors conclude that: 

i) 7/10 technical patterns analyzed provide incremental information, especially 
on Nasdaq stocks. However, this does not necessarily imply that the information 
can be successfully used to generate excess trading profits. 

ii) It may be possible to detect 'optimal' patterns to predict phenomena in a 
financial time series, for e.g. a change in regime. 

**[@bruder2011trend] - Trend Filtering Methods for Momentum Strategies**

The paper analyzes different trend filtering methods and their advantages and 
disadvantages. Trend filtering methods studied include: 

1) Linear Methods 
a) Convolution representation - A linear trend kernel is applied to the time 
series to extract a smoother time series 
b) Measuring Trend and it's derivative - Apply the black schoeles model and 
Brownian motion
c) Moving average filters 
d) Least squares filters 

2) Non-linear Methods 
a) Non-parametric regression - Kernel regression, Loess regression, Spline 
regression, local polynomial regression
b) L1 filter - Hodrick-Prescott generalization
c) Wavelet filtering - Fourier transformation 
d) Other methods - singular spectrum analysis, support vector machines, empirical mode decomposition 

[https://tradersbulletin.co.uk/combining-trend-following-and-mean-reversion/](Combining trend and mean reversion)

Grundy and McNichols (1989) and Blume, Easley,
and O’Hara (1994) show that trading volume can provide useful information beyond prices

Hong and Stein (1999) explain that, at the
start of a trend, investors underreact to news; as the market rises, investors subsequently overreact,
leading to even higher prices.

**Market timing with moving averages:**
Summing up the results presented above, all technical trading indicators considered in this
paper are computed in the same general manner. We nd, for instance, that the computation
of every technical trading indicator can be interpreted as the computation of a weighted average
of the momentum rules computed using different averaging periods. Thus, the momentum rule
might be considered as an elementary trading rule on the basis of which one can construct
more elaborate rules.

equal weighting of price changes (as in the MOM rule), underweighting the most old price changes (as in the P-MA
rule or in the most .MA rules), and underweighting both the most recent and the most old
price changes (as in the DCM)

For practitioners, it is comforting to know that the popular DCM rule, where one
uses 50-day and 200-day simple moving averages, is very close to the best performing rule for
timing the Standard and Poor's 500 index.

Zakamulin (2015) entertains a method of nding
the most robust moving average weighting scheme, where \robustness" of a weighting scheme
is dened as its ability to generate sustainable performance under all possible market scenarios
regardless of the size of the averaging window. He nds that the CV-EMA weighting scheme
with a decay factor of 0.85-0.90 produces the most robust performance.

# Papers on Mean Reversion 
